application: dacresni
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: / 
  static_files: index.html
  upload: index.html

- url: /index.html 
  static_files: index.html
  upload: index.html



- url: /mantext
  static_dir: mantext

- url: /media/
  static_dir: media

libraries:
- name: jinja2
  version: "2.6"
