application: dacresni
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /.*
  script: main.py

- url: /mantext
  static_dir: mantext

- url: /static
  static_dir: media

libraries:
- name: jinja2
  version: "1.2"
